
networks:
  dev_network:

services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      BACKEND: ${BACKEND}
      BROKER: ${BROKER}
    depends_on:
      - redis
    networks:
      dev_network:
    volumes:
      - ./:/app

  app:
    build:
      context: .
    environment:
      BACKEND: ${BACKEND}
      BROKER: ${BROKER}
    depends_on:
      - redis
    networks:
      dev_network:
    volumes:
      - ./:/app



